In [1]:
import pandas as pd

Load data

In [6]:
datapath = '../datasets/Sweco/buurt_all_new.csv'
data = pd.read_csv(datapath, sep=',', header=[0], index_col=[0])

In [7]:
data.head()

,year,gm_naam,gwb_code,gwb_code_10_x,gwb_code_10_y,gwb_code_8,regio,fine_dust,grime,nitrogen_dioxide,...,wcorpw,woning,woz,00_14,15_24,1gezw,25_44,3km_sc,45_64,65_oo
0,2013,Appingedam,WK000300,WK000300,BU00030000,300,Wijk 00,NaN,0.45,12.50,...,42.0,5785,149.0,15.0,10.0,73.0,22.0,NaN,30.0,22.0
1,2013,Appingedam,WK000300,WK000300,BU00030007,300,Wijk 00,NaN,0.40,11.36,...,42.0,5785,149.0,15.0,10.0,73.0,22.0,NaN,30.0,22.0
2,2013,Appingedam,WK000300,WK000300,BU00030008,300,Wijk 00,NaN,0.41,11.85,...,42.0,5785,149.0,15.0,10.0,73.0,22.0,NaN,30.0,22.0
3,2013,Appingedam,WK000300,WK000300,BU00030001,300,Wijk 00,NaN,0.44,12.32,...,42.0,5785,149.0,15.0,10.0,73.0,22.0,NaN,30.0,22.0
4,2013,Appingedam,WK000300,WK000300,BU00030009,300,Wijk 00,NaN,0.42,11.90,...,42.0,5785,149.0,15.0,10.0,73.0,22.0,NaN,30.0,22.0

In [21]:
data = data[['gwb_code', 'gwb_code_10_y', 'fine_dust', 'grime', 'nitrogen_dioxide', 'woz']].copy()